substitutions:
  room: "Bedroom"

esphome:
  name: bedroom

esp8266:
  board: d1_mini

# Enable logging
logger:

<<: !include common/env.yaml

remote_transmitter:
  pin: D5
  carrier_duty_percent: 50

i2c:
  scan: true

sensor:
  - <<: !include common/sensor/sht30.yaml

climate:
  - <<: !include common/climate/ac.yaml
    sensor: sht30_temperature

light:
  - <<: !include common/light/panasonic.yaml

output:
  - <<: !include common/output/panasonic_light_out.yaml
