substitutions:
  room: "Living Room"

esphome:
  name: livingroom_sensors

esp8266:
  board: d1_mini

# Enable logging
logger:

<<: !include common/env.yaml

i2c:
  scan: true

uart:
  rx_pin: D6
  tx_pin: D7
  baud_rate: 9600

sensor:
  - <<: !include common/sensor/sht30.yaml
  - <<: !include common/sensor/bmp180.yaml
  - <<: !include common/sensor/s8.yaml
