<<: !include fallback.yaml

bk72xx:
  board: wb3s #generic-bk7231t-qfn32-tuya

preferences:
  # without this it seemed to be constantly writing to flash for no reason I could identify.
  flash_write_interval: 1days

remote_transmitter:
  pin:
    number: PWM5 # P26
    mode:
      output: true
  carrier_duty_percent: 50

remote_receiver:
  pin:
    number: P8
    inverted: true
    mode:
      input: true
      pullup: true

uart:
  rx_pin: RX1
  tx_pin: TX1
  baud_rate: 9600

tuya:

sensor:
  - platform: tuya
    id: tuya_temperature
    sensor_datapoint: 101
    name: "${room} Temperature"
    unit_of_measurement: ""
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: tuya
    id: tuya_humidity
    sensor_datapoint: 102
    name: "${room} Humidity"
    unit_of_measurement: "%"

